HW5 is completed
frobbery/go_course pull request #5
Opened 2024-12-28 14:19 UTC by frobbery

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-12-28 15:39 UTC, ityulkanov requested changes

2024-12-28 15:39 UTC, ityulkanov commented on hw05_parallel_execution/run.go
> +		task := tasks[currTaskIndex]
ДЗ направлено на обучение студента использованию примитивов синхронизации - атомиков, каналов, вейтгрупп. Поэтому для синхронизации исполнения горутин необходимо использовать каналы. Подсказка: создаём горутины, вычитывающие наш канал.
Потом загружаем в канал таски, проверяя что не превышено количество ошибок при этом. 
Также для более полного понимания каналов, рекомендую вам ознакомиться со следующей [статьёй](https://habr.com/ru/articles/490336/)

2024-12-29 11:57 UTC, frobbery commented on hw05_parallel_execution/run.go
> +		task := tasks[currTaskIndex]
Добавила использование каналов

2024-12-29 19:14 UTC, ityulkanov commented on hw05_parallel_execution/run.go
> +		if errCount.errorNumber < maxErrorNumber || maxErrorNumber <= 0 {
тут бы я предложил использовать так называемый early return, он упростит логику и понимание происходящего. 
Т.е. сначала отсекаем все невалидные кейсы, потом исполняем основную бизнес логику

2024-12-29 19:15 UTC, ityulkanov commented on hw05_parallel_execution/run.go
> +	go addTasks(&taskChan, tasks, &wg)
```suggestion
	addTasks(&taskChan, tasks, &wg)
```
горутина нам тут не нужна

2024-12-31 06:07 UTC, ityulkanov commented on hw05_parallel_execution/run.go
> +			}
Осталось только эту часть поправить, как я писал, и приму

2024-12-31 10:32 UTC, ityulkanov approved these changes

2024-12-31 12:42 UTC, merged